### ISSUE TITLE
フィルタオブジェクトとして使用できるようにして欲しい

### ISSUE THREAD

**Issue by hebiiro** [Pachira762/Real-xxxGAN-filter#1]
モードをトラックバーにして FILTER_FLAG_RADIO_BUTTON を使わないようにしてほしいです。
そうすると拡張編集のタイムラインにフィルタオブジェクトとして配置できるはずなので使い勝手が良くなると思います。

**Comment by Pachira762** [comment]
レスポンスありがとうございます。
フィルタオブジェクトの条件があったんですね。
対応してみます。

**Comment by hebiiro** [comment]
ありがとうございます。

**Comment by hebiiro** [comment]
動作確認できました、ありがとうございました。
